version: '3'
services:
  kanboard:
    build:
      context: .
      args:
        KANBOARD_DB_PASSWD: doihavesuffisciententropyyesido
        KANBOARD_VERSION: 1.2.10
    links:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - kanboard-data:/var/www/kanboard
  
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: doihavesuffisciententropyyesido
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: doihavesuffisciententropyyesido


volumes:
  kanboard-data:
